---
title: "Data Manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

## load in the FAS litters Data

```{r}
litter_df = read_csv("./data/FAS_litters.csv")
litter_df = janitor::clean_names(litter_df)
```

## `select`

Choose some columns and not others.

```{r}
select(litter_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litter_df, -litter_number)
```

Renaming columns...

```{r}
select(litter_df, GROUP = group, LITTer_NUmBer = litter_number)
```

```{r}
rename(litter_df, GROUP = group, LITTer_NUmBer = litter_number)
```

Select helpers

```{r}
select(litter_df, starts_with("gd"))
```

```{r}
select(litter_df, litter_number, everything())
```

```{r}
relocate(litter_df, litter_number)
```

## `filter`

```{r}
filter(litter_df, gd0_weight < 22)
```

```{r}
filter(litter_df, gd0_weight >= 22)
```

```{r}
filter(litter_df, gd_of_birth == 20)
```

```{r}
filter(litter_df, !(gd_of_birth == 20))
```

```{r}
filter(litter_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litter_df, group == "Mod8")
```

# If want the combination of both names in the group
```{r}
filter(litter_df, group %in% c("Con7", "Mod8"))
```

## `mutate`

```{r}
mutate(litter_df, 
       wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```

## `arrange`

```{r}
arrange(litter_df, pups_born_alive)
```

## `%>%`

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight)
```

USE THE PIPE OPERATION INSTEAD

```{r}
litter_df = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(gd0_weight)
  
```


